from sympy import *
x,y,z=symbols(' x y z' )
f=x**2+2*y**2+3*z**2-2*x*y-2*x*z
print('Анализируемая функция f  для переменных x,y,z -\n f= ', f )
print('Необходимые условия экстремума')
fx=f.diff(x)
print('df/dx =', fx, '=0')
fy=f.diff(y)
print('df/dy =', fy, '=0')
fz=f.diff(z)
print('df/dz =', fz, '=0')
sols=solve([fx, fy, fz], x, y, z)
print('Стационарные точки M(x,y,z) -',sols)
print('Вторые производные в точке М')
fxx=f.diff(x,x).subs({x:sols[x],y:sols[y],z:sols[z]})
print('fxx=',fxx)
fxy=f.diff(x,y).subs({x:sols[x],y:sols[y],z:sols[z]})
print('fxy=',fxy)
fxz=f.diff(x,z).subs({x:sols[x],y:sols[y],z:sols[z]})
print('fxz=',fxz)
fyx=f.diff(y,x).subs({x:sols[x],y:sols[y],z:sols[z]})
print('fyx=',fyx)
fyy=f.diff(y,y).subs({x:sols[x],y:sols[y],z:sols[z]})
print('fyy=',fyy)
fyz=f.diff(y,z).subs({x:sols[x],y:sols[y],z:sols[z]})
print('fyz=',fyz)
fzx=f.diff(z,x).subs({x:sols[x],y:sols[y],z:sols[z]})
print('fzx=',fzx)
fzy=f.diff(z,y).subs({x:sols[x],y:sols[y],z:sols[z]})
print('fzy=',fzy)
fzz=f.diff(z,z).subs({x:sols[x],y:sols[y],z:sols[z]})
print('fzz=',fzz)
print('Расчёт определителей матрицы Гессе \n («разрастаются» из левого верхнего угла)')
d1=fxx
print('Определитель М1- d1=',d1)
M2=Matrix([[fxx,fxy],[fyx,fyy]])
print('Матрица М2-',M2)
d2=M2.det()
print('Определитель М2- d2=',d2)
M3=Matrix([[fxx,fxy,fxz],[fyx,fyy,fyz],[fzx,fzy,fzz]])
print('Матрица М3-',M3)
d3=M3.det()
print('Определитель М3- d3=',d3)
print ('Достаточные условия экстремума')
if  d1>0 and d2>0 and d3>0:
         print('При d1=%s,>0, d2=%s>0, d3=%s>0, минимум f в точке М(%s,%s,%s)'%(str(d1),str(d2),str(d3),str(sols[x]),str(sols[y]),str(sols[z])))
elif  d1<0 and d2>0 and d3<0:
         print('При d1=%s,<0, d2=%s>0, d3=%s<0,максимум f в точке М(%s,%s,%s)'%(str(d1),str(d2),str(d3),str(sols[x]),str(sols[y]),str(sols[z])))
elif  d3!=0:
         print('Седло в точке М(%s,%s,%s)'%(str(sols[x]),str(sols[y]),str(sols[z])))
else:
          print('Нет экстремума в точке М(%s,%s,%s)'%(str(sols[x]),str(sols[y]),str(sols[z])))
r=f.subs({x:sols[x],y:sols[y],z:sols[z]})
print('Значение %s функции в точке М(%s,%s,%s)'%(str(r),str(sols[x]),str(sols[y]),str(sols[z])))